name: yuki-no

on:
  schedule:
    # JST 3,11,15,19,23時に実行（本家のコミットが少ない 4-9 時台は停止）
    - cron: '0 2,6,10,14,18 * * *'
  workflow_dispatch:

permissions:
  # 追跡元リポジトリーの変更を読む
  contents: read
  # 差分更新の issue を作成・更新する
  issues: write
  # 前回の実行情報を取得する
  actions: read

jobs:
  yuki-no:
    name: Yuki-no
    runs-on: ubuntu-latest
    steps:
      - uses: Gumball12/yuki-no@6379b1eeb16492952331d3cea3f7dd4685768eb4 # v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          head-repo: https://github.com/vuejs/docs
          head-repo-branch: main
          track-from: 7681134fd8505e61a265d161d73d28acb3c74822
